version: '3.8'

services:
  backend:
    build: .
    container_name: social-media-api
    ports:
      - '5000:5000'
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: saptadev27
      POSTGRES_PASSWORD: saptadev27
      POSTGRES_DB: socialmediaengagementapi
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
